#!/bin/bash
MODEL_NAME="BeTSSi"
#MODEL_NAME="sphere_320" #sphere_320, sphere_1280, sphere_5120, sphere_20480
NP=7    	# Number of processors
name=${1:-$MODEL_NAME}
if [ -z "$DISPLAY" ]
then
	echo "Error: set the DISPLAY variable" #The display variable should be set for post processing purposes in paraview. This issue arises when using screen, and can be resolved by first getting the display variable outside the screen session (echo $DISPLAY) and then inside the screen session setting the variable to this value (i.e. export DISPLAY=localhost:10.0)"
fi

DICTS="0/epsilon 0/k 0/nut 0/nuTilda 0/omega 0/p 0/s 0/U \
       constant/transportProperties \
       system/blockMeshDict system/decomposeParDict system/controlDict system/surfaceFeatureExtractDict system/snappyHexMeshDict \
			 postProcScript.py"
SED_VARIABLES="DX_FRNT DX_BCK DZ_TOP DZ_BT DY MESH RE \
							 NP START_TIME END_TIME DELTA_T U_INF AREF LREF SIMULATION_TYPE \
							 EPSILON_0 K_0 NUT_0 OMEGA_0 NU MODEL_NAME WRITE_INTERVAL PURGE_WRITE STRIDE"
for MESH in 1
do
	pathToFolder="$HOME/results/openfoam/"$name"_MESH_"$MESH
	rm -rf $pathToFolder/*
	mkdir -p $pathToFolder
	cp -r ./* $pathToFolder
	
	pushd $pathToFolder > /dev/null
	source ./parameters
	source $HOME/kode/bashScripts/sedFiles
			
	blockMesh
	surfaceFeatureExtract
	snappyHexMesh -overwrite

	
	decomposePar
	mpirun -np $NP pisoFoam -parallel
	
	python3 convertDatToCSV.py
	python3 exportResults.py --inputname="postProcessing/forceCoeffs/0/coefficient.dat" --outputname="results_OF_$MESH.txt" --openfoam
	cat results_OF_$MESH.txt
	
#	mpiexec -n $NP ~/programs/paraview_build/bin/pvbatch postProcScript.py -mpi 
	paraview --script=postProcScript.py
	popd > /dev/null
done
