#!/bin/sh
name=${1:-cylinder}
mkdir -p ~/OpenFOAM/OpenFOAM-v1912/run/$name
cp -r ./* ~/OpenFOAM/OpenFOAM-v1912/run/$name/
cd ~/OpenFOAM/OpenFOAM-v1912/run/$name/

rm -r -f 0.* [1-9]* 0/polyMesh postProcessing constant/extendedFeatureEdgeMesh constant/polyMesh VTK processor* dynamicCode
np=$(cat constant/parameters | grep -oP '(?<=np )[0-9]+')

blockMesh

#pisoFoam

decomposePar
mpirun -np $np pisoFoam -parallel
reconstructPar
postProcess -func vorticity
python convertDatToCSV.py
python exportResults.py && cat results.txt 
paraFoam --script=postProcScript.py

#for (( n=0; n<$np; n++ ))
#do
#  cd processor$n && foamToVTK && cd ..
#done
#paraFoam
