#!/bin/bash
MODEL_NAME="$1"
NU=0.01     			# kinematic viscosity
NP=$2            	# Number of processors
MESH=$4            # Mesh number: MESH = 1, 2, 3, ...
START_TIME=0      # Start time for simulation
END_TIME=1000     # End time for simulation
DIAM=1.0          # Diameter of cylinder
LENGTH=1.0        # Length of cylinder
OMEGA_ROT=0.0     # Angular velocity of cylinder rotation
U_INF=1.0         # incident velocity speed
BDD=64            # ratio between height of domain and diameter of cylinder
WRITE_INTERVAL=10  # Writes data every writeInterval time steps
PURGE_WRITE=2     # Integer representing a limit on the number of time directories 
                  # that are stored by overwriting time directories on a cyclic basis
SOLVER='iterative'
SED_V_CLASS=petsc
SED_P_CLASS=petsc
if [[ $5 == 'iterative' ]]
then
	SED_V_TYPE=gmres
	SED_V_PC=asm
	SED_V_PACKAGE=petsc
	SED_P_TYPE=$SED_V_TYPE
	SED_P_PC=gamg
	SED_P_PACKAGE=$SED_V_PACKAGE
else
	SED_V_TYPE=preonly
	SED_V_PC=lu
	SED_V_PACKAGE=mumps
	SED_P_TYPE=$SED_V_TYPE
	SED_P_PC=$SED_V_TYPE
	SED_P_PACKAGE=$SED_V_PACKAGE
fi

STRIDE=$WRITE_INTERVAL									
LREF=$LENGTH
NRE_0=$(echo "5*2^($MESH-6)" | bc -l) 				  # minimum number of elements withing D/sqrt(Re) outside cylinder
DELTA_T=$(echo "1/(10*2^($MESH-5))" | bc -l)   # Discretization time step
AREF=$(echo "$DIAM*$LENGTH" | bc -l)
Um=$(echo "0.05*$U_INF" | bc -l)
l=$(echo "0.2*$DIAM" | bc -l)
K_0=$(echo "3/2*$Um^2" | bc -l)
C=0.16431676725 #0.09^0.75
EPSILON_0=$(echo "$C*sqrt($K_0^3)/$l" | bc -l)
OMEGA_0=$(echo "sqrt($K_0)/$l" | bc -l)
NUT_0=$(echo "0.09*$K_0^2/$EPSILON_0" | bc -l)
RE=$(echo "sqrt($U_INF^2)*$DIAM/$NU" | bc -l)

# DICTS contains the set of files at which we want to replace the variables in SED_VARIABLES
if [[ $3 == "openfoam" ]]; then
	DICTS="0/epsilon 0/k 0/nut 0/nuTilda 0/omega 0/p 0/s 0/U \
       constant/transportProperties \
       system/decomposeParDict system/controlDict \
			 postProcScript.py generate_blockMeshDict_file.c"
else
	DICTS="generate_blockMeshDict_file.c Cylinder2D-template.xinp Cylinder2D_chorin-template.xinp"
fi
SED_VARIABLES="BDD DIAM LENGTH NRE_0 RE MESH OMEGA_ROT \
							 NP START_TIME END_TIME DELTA_T U_INF AREF LREF \
							 EPSILON_0 K_0 NUT_0 OMEGA_0 NU MODEL_NAME WRITE_INTERVAL PURGE_WRITE STRIDE
							 V_CLASS P_CLASS V_TYPE V_PC V_PACKAGE P_TYPE P_PC P_PACKAGE"

for DICT in $DICTS 
do
	for SED_VARIABLE in $SED_VARIABLES
	do
		eval "SED_VARIABLE_VALUE=\$$SED_VARIABLE"
		sed -i "s/SED_$SED_VARIABLE/$SED_VARIABLE_VALUE/g" $DICT
	done
done

